### ISSUE TITLE
Question about camera rotation matrix in backward_oculusion_aware_render

### ISSUE THREAD

**Issue by junwuzhang19** [kongdai123/repainting_3d_assets#3]
Thanks for your great work! I wonder why you add 180° to azim_angles(i.e., cur_angle - next_angle) in backward_oculusion_aware_render.
https://github.com/kongdai123/repainting_3d_assets/blob/256af2cbeceaa009cf67fa424de85a161355c4b7/repainting_3d_assets/view_generation/reproj.py#L200
And I also notice you removed 180° in render_depth_map, which I understand. I hope you can help me out. Thanks!
https://github.com/kongdai123/repainting_3d_assets/blob/256af2cbeceaa009cf67fa424de85a161355c4b7/repainting_3d_assets/view_generation/reproj.py#L76

**Comment by kongdai123** [comment]
Hi, thanks for your interest in our work, please check the pytorch3D documentation for generating the rotation matrix, https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/cameras.html#look_at_rotation, it returns the identity matrix for azimuth = 180 degrees, this is why we add 180 to the relative transforms.

**Comment by kongdai123** [comment]
Please feel free to comment if you have more questions
