### ISSUE TITLE
Question about norm_mask generation?

### ISSUE THREAD

**Issue by whiteinblue** [kongdai123/repainting_3d_assets#4]
in line 290 of file from view_generation/reproj.py.
norm_mask is generated with following code:
**************
  norm_mask = (
      (normals < normal_thresh)
      * (next_normal > normal) #question on this line
      * (~occlu_mask)
      * (depth_tensor_next != depth_tensor_next.max())
  )
****************
As next_normal and normal generated by next_view and current_view separately, pixels on next_normal and normal  correspond to different positions of 3D object, can it  be compared directly? 
Or it should be  replaced by next_normal > normals ?

**Comment by kongdai123** [comment]
Hi, thanks for you interest in our work. We assign the visibility score to each fragment as a dot product between the surface normal and the unit vector originating in the camera origin and pointing at the fragment. We compare the visibility scores between the previous and novel views' fragments. I hope this resolves your concern.
