### ISSUE TITLE
why the saved model without texture map?

### ISSUE THREAD

**Issue by No360201** [kongdai123/repainting_3d_assets#5]
this is the video
https://github.com/kongdai123/repainting_3d_assets/assets/57511687/23e25b66-6c85-4cb2-9e69-821471f3d7e7

but the model without texture map
[saved_model.zip](https://github.com/kongdai123/repainting_3d_assets/files/12846002/saved_model.zip)

**Comment by kongdai123** [comment]
Hi, thank you for your interest in our project. We do not save our colors in the texture map format, as our method works for meshes without texture maps, instead we save it as vertex colors, the .ply file in the zip file you sent contains colors, you can  view it with an application that supports vertex colors. E.g. MeshLab

**Comment by toshas** [comment]
One more thing: if needed, the original model's texture can be repopulated from the output model verticex colors

**Comment by No360201** [comment]
> One more thing: if needed, the original model's texture can be repopulated from the output model verticex colors
could you please show me the code to  repopulate the texture from verticex colors ? thank you very much.
